### ISSUE TITLE
Not compiling c++ code giving error of not able to open external programme msbuild.

### ISSUE THREAD

**Issue by SPK-RPI** [headmelted/codebuilds#11]
complile a new one

**Comment by headmelted** [comment]
There were some build issues to do with heap size that were also impacting the upstream codebase. These are now resolved and a new build has been deployed. Can you update and confirm if this issue still exists?

**Comment by headmelted** [comment]
The code has now been adapted for Github/Travis CI and is now released to this repository.

Can you try installing the latest version for your architecture to confirm if this fixes your problem?

**Comment by headmelted** [comment]
Closing this out as I haven't heard anything in some time - please re-open if this is still an issue.
