### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by varlevi** [headmelted/codebuilds#111]
Hey! I love VS Code and am SO happy to have it on my Raspberry Pi now! However, I don't like the app icon that shows up in docks and application websites and it doesn't fit with my custom icon sets. Is there a way to replace the icon with a custom one?

**Comment by cellcoresystems** [comment]
@varlevi if you think about it yourself: How would you do it to change any icon oder image from any application?

I would say search for it :o) and you will find it here or a on a similar location:

`/usr/share/code-oss/resources/app/resources/linux/code.png`

exchange it to anything you like.

**Comment by varlevi** [comment]
Thanks @cellcoresystems! Unfortunately, computer restrictions made me unable to add files to the ```/usr/share/code-oss/etc...``` directory, but I was able to redirect my system to a different location so the new app icon is used in docks and menus. Unfortunately, it doesn't change the icon inside the application, but I was really only annoyed because the icon didn't fit with my system design. It doesn't clash nearly as much with VS Code itself.
