### ISSUE TITLE
Support for vscode-icons

### ISSUE THREAD

**Issue by 40tude** [headmelted/codebuilds#13]
Bonjour
I used to compile VSCode myself on Raspberry. However, since version 1.1 it seems I'm no longer able to do it. At the end, I decided to download the deb installer on the site. Everything works like a charm. Thank you very much.

One point that may help others
If one want to install **vscode-icons** extension he must edit the file /usr/share/code-oss/ressources/app/package.json and set the "name" to "Code" (and nothing else)
This can be done even if the extension is already installed and no icon show up in the Explorer tab.

Regards, Philippe

**Comment by headmelted** [comment]
Noted.

I've just writte this on a few other tickets but I've been toiling away on some changes that will bring all of the build system into the open, and onto Github.  There were some technical challenges involved in this, but I've been writing up what's changed for when I get it released (very soon).

Sorry for the lack of recent builds, I promise the wait will have been worth it. :-)

**Comment by headmelted** [comment]
The builds have now been updated and are on github, inside this repository.

Can you try installing the latest deb file for your architecture (armhf) from the releases page? (problems with bintray at the minute).
