### ISSUE TITLE
Visual Studio Code 1.50 adds official builds making this build obsolete?

### ISSUE THREAD

**Issue by TheOtterlord** [headmelted/codebuilds#134]
Visual Studio Code's [September update (1.50)](https://code.visualstudio.com/updates/v1_50#_linux-arm-builds) introduces official builds for ARMv7 and ARM64 architectures and as the changelog states. 

> "This means you can now officially use VS Code on a Raspberry Pi, Chromebook, and other ARM-based devices!" - VS Code v1.15 changelog

As far as I can see, there are no builds here that are not available on the [official download page](https://code.visualstudio.com/#alt-downloads). 

If this does mean the end, I would just like to thank everyone who has worked on this up until now as I've been using this build as my main editor on my Pi 4 and it's helped me so much.

**Comment by rogueturnip** [comment]
Wouldn't work on my Lenovo Chromebook Duet.  It's looking for a number of dependancies that have :arm64 in them.  The linux beta on the duet doesn't put :arm64 so it won't install.

**Comment by rogueturnip** [comment]
I got it to work but by using the tar.gz.

**Comment by floreseken** [comment]
@rogueturnip could you share some details on how you did that?
