### ISSUE TITLE
Nightly or Montly builds :-)

### ISSUE THREAD

**Issue by 40tude** [headmelted/codebuilds#17]
Bonjour
Do you know when the next build will occur?
I just visited the site the the last buld is from Feb 22
Best regards, Philippe

**Comment by headmelted** [comment]
Working on it. :-)

I'm trying to divide time at the moment between this and working on a PR that would bring official ARM support to the main vscode repo, unfortunately finding the time has been difficult in the last few weeks.

**Comment by headmelted** [comment]
So I've identified the problem as being related to this issue in one of the core dependencies:

https://github.com/roblourens/vscode-ripgrep/issues/1

If that issue is fixed, the nightly merge should automatically right itself. If not,

**Comment by headmelted** [comment]
[Sorry, on phone and that was an errant click above.]

If the merge does not right itself I'll look at building out the dependency separately for ARM to get the builds restored.

**Comment by headmelted** [comment]
Sorry for the further delays, but update now inbound asap that will bring everything onto Github (part of the cross-compilation system was not compatible with Travis - I'm finishing up some final changes here to get everything running on Github so it can be contributed to).

**Comment by headmelted** [comment]
Code now on Github, and new releases available 👍
