### ISSUE TITLE
Code for the code that installs the Code?

### ISSUE THREAD

**Issue by JELaVallee** [headmelted/codebuilds#18]
Just wondering... I can pull down your shell scripts and thwack at them, but how about putting them up here so we can be real OSS champs with it?

I'd like to be able to provide a CLI arg interface for injecting target and release params at the least...  Or a mondo script that would parse ENV and args and produce an appropriate installation?

Or maybe something that could chroot-launcher-bind any stock ubuntu app?

All of these dreams will be tears in the rain... if you don't provide open code.

JustSayin',
Etienne

**Comment by headmelted** [comment]
Absolutely, I've been thinking the same myself.

I'm actually working on it right now.

I should also mention for anyone that didn't catch this on
HN/reddit/medium/Github that the reason I haven't updated the builds lately
is that I've been reworking them into a form that works with Travis CI so I
could contribute the ARM support back into the upstream Microsoft
repository.

Which is now done, and it's on the May 2017 roadmap pending review. :-)

I'll prioritize getting the scripts onto Github asap though so you can
contribute/inspect :-)

**Comment by JELaVallee** [comment]
Thanks, @headmelted I'm looking at finding a way of making ChromeOS on a "beefy" hardware platform (I'm on an 8gb loner Asus C302CA flipbook with an M3 processor) into a viable CloudOps development system.  Anything that I can contribute to a more "unified ChromeOS/Chroot installation" tool will make my life a lot more bearable... not to mention the number of devs who just need Github, AWS/GoogleCloud/Azure and a basic CLI that can support NG2, Node, Python, Terraform, Ansible and Docker... 

I've got a stack that does most of that with VSCode, Atom and Intellij/Webstorm/PHPStorm, but I'm looking for a more on-stop-scaffold solution.  Be cool if we could massage this into such... 

cheers,
Etienne

**Comment by JELaVallee** [comment]
And yes, I could work it out with a C9 configuration and deployment script, but I like what you're doing here with VS Code as the core deployment for a much more robust development model.  Tools, frameworks and infra needs should be the inputs to an IDE... not the other way around... JustSayin'.

**Comment by JELaVallee** [comment]
So, how about a script that takes a number of config/env/code-needs params and then exposed an architecture that could be fed back to a `template` model for this tool/script?  Then folks could define a common YML structure that would drive complex build models, but from the get-go could get a VS Code installation with the basics like Stock-ES5 app build tools, NodeJS tools, and AWS deployment CFTs, but could be extended to support something as extended as GoCode build tools, Alpine env, and Azure deployment artifacts w/o much more than those target's basic config artifacts?

**Comment by JELaVallee** [comment]
And this is where I throw in my love for terraform, ansibile-ishness and docker as my own prefered tools for this... but I'd be down with puppet, packer.io and opencloud if the needs required it... 

And so, I'm looking to create a unified environment definition model and an infrastructure definition model that is independent of the implementation code langs/libs and can still expose the various `watch`, `test`, `build`, `integration-validation` and `production` executions scripts my team needs.

Amazing that I'm willing to build a deployment framework from this, to be honest...

**Comment by headmelted** [comment]
Hey, sorry for the lack of updates and comeback on this.

I'm working on some big changes that will help bring all of this into the open, and give it a much more stable footing for the future.  When I get it ready (as soon as I possibly can), your help with scripts and PRs will be not only welcome but gratefully appreciated! :-)

One thing to note though is that you'll need to sign the Microsoft CLA on their Github (so we can contribute any changes that are relevant back upstream).

**Comment by JELaVallee** [comment]
@headmelted 

S'all good... Been experimenting with xiwi and the whole crouton/chromeos-flavored-chroot space...

Just landed a great little ASUS C302CA Flip machine and absolutely loving it as a webdev and devops "fly-weight" platform... really impressed thus far.  My MacBookPro is definitely feeling neglected. ;-)

Fiddling with the feasibility of a chrome extension that could act as an installation shell for a NativeService "xiwi-launchpad", with the goal of using it as a bridge for being able to launch xiwi-apps via the ChromeOS launcher.  Config of which would let you map chroot-side apps to ChromeOS side desktop experience.  Anyway... cool environment.

**Comment by headmelted** [comment]
Code is now up on github 👍
