### ISSUE TITLE
Installation abort On raspberry Pi with latest O/S version

### ISSUE THREAD

**Issue by jadupl2** [headmelted/codebuilds#20]
- VSCode Version: Trying to install 
- OS Version: root@raspi3~# uname -a
Linux raspi3.maison.ca 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

Steps to Reproduce:

1.Run the installer (See screen output below)
2.
root@raspi3~# uname -a
Linux raspi3.maison.ca 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

root@raspi3~# cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi

root@raspi3~# . <( wget -O - https://code.headmelted.com/installers/apt.sh )
--2017-05-21 10:55:35--  https://code.headmelted.com/installers/apt.sh
Resolving code.headmelted.com (code.headmelted.com)... 104.27.187.80, 104.27.186.80, 2400:cb00:2048:1::681b:bb50, ...
Connecting to code.headmelted.com (code.headmelted.com)|104.27.187.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-sh]
Saving to: ‘STDOUT’
-                                                [ <=>                                                                                             ]   2.26K  --.-KB/s   in 0.001s
2017-05-21 10:55:35 (3.77 MB/s) - written to stdout [2313]
Detecting architecture...
Architecture detected as armv7l...
Installing bintray GPG key...
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.j3Gh0veG7K --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
gpg: requesting key D401AB61 from hkp server keyserver.ubuntu.com
gpg: key D401AB61: "Bintray (by JFrog) <bintray@bintray.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Done!
Installing headmelted GPG key...
OK
Done!
Installing headmelted repository...
deb https://dl.bintray.com/headmelted/deb-code-oss
Repository install complete.
Updating APT cache...
E: Malformed line 4 in source list /etc/apt/sources.list (dist)
E: The list of sources could not be read.
Done!
Installing Visual Studio Code...
**Reading package lists... Error!
E: Malformed line 4 in source list /etc/apt/sources.list (dist)
E: The list of sources could not be read.
E: The package lists or status file could not be parsed or opened.
Visual Studio Code install failed.
Connection to raspi3 closed.**

Reconnect to raspberry Pi because connection was closed
root@holmes:~# ssh raspi3
Last login: Sun May 21 10:52:26 2017 from holmes.maison.ca

root@raspi3~# cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi
deb https://dl.bintray.com/headmelted/deb-code-oss
root@raspi3~#

**Comment by cuibonobo** [comment]
I have found that in order to fix the 'Malformed line' error, the line in `/etc/apt/sources.list` should be changed from this:

```
deb https://dl.bintray.com/headmelted/deb-code-oss
```

...to this:

```
deb https://dl.bintray.com/headmelted/deb-code-oss/ wheezy main
```

To finish the installation, update your `apt-get` sources and then install `code-oss`:

```bash
apt-get update
apt-get install -y code-oss
```

**Comment by cuibonobo** [comment]
I considered making a pull request to fix this issue, but I'm not sure if the edits to `sources.list` will break something on previous versions. Would you happen to know, @headmelted?

**Comment by jadupl2** [comment]
Thank You !!!

**Comment by headmelted** [comment]
Hi, I've now switched the repository from bintray to packagecloud (bintray abruptly locked the repo and asked me to use their artifactory product instead, frustratingly).

Can you try a **_fresh_** install from the script now on the website (so I know you're also running the latest build) and post back here your result?

**Comment by jadupl2** [comment]
Just Tried it seem to install correctly, but when I run "code-oss" nothing
happen .
See Screen output below

root@raspi3/etc# . <( wget -O -
https://code.headmelted.com/installers/apt.sh )
--2017-06-14 09:20:38--  https://code.headmelted.com/installers/apt.sh
Resolving code.headmelted.com (code.headmelted.com)... 104.27.186.80,
104.27.187.80, 2400:cb00:2048:1::681b:bb50, ...
Connecting to code.headmelted.com (code.headmelted.com)|104.27.186.80|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-sh]
Saving to: ‘STDOUT’

-                           [ <=>                           ]   2.29K
 --.-KB/s   in 0.001s

2017-06-14 09:20:38 (3.10 MB/s) - written to stdout [2340]

Detecting architecture...
Architecture detected as armv7l...
Installing headmelted GPG key...
OK
Done!
Installing headmelted repository...
deb https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial main
Repository install complete.
Updating APT cache...
Get:1 http://mirrordirector.raspbian.org jessie InRelease [14.9 kB]
Get:2 http://archive.raspberrypi.org jessie InRelease [22.9 kB]
Get:3 https://packagecloud.io xenial InRelease [23.4 kB]
Get:4 http://mirrordirector.raspbian.org jessie/main armhf Packages [9,532
kB]
Get:5 https://packagecloud.io xenial/main armhf Packages [5,080 B]
Get:6 http://archive.raspberrypi.org jessie/main armhf Packages [163 kB]

Get:7 https://packagecloud.io xenial/main Translation-en_CA [162 B]

Get:8 http://archive.raspberrypi.org jessie/ui armhf Packages [57.9 kB]

Get:9 https://packagecloud.io xenial/main Translation-en [162 B]

Get:10 https://packagecloud.io xenial/main Translation-en_CA [162 B]

Get:11 https://packagecloud.io xenial/main Translation-en [162 B]

Get:12 https://packagecloud.io xenial/main Translation-en_CA [162 B]

Get:13 https://packagecloud.io xenial/main Translation-en [162 B]

Get:14 http://mirrordirector.raspbian.org jessie/contrib armhf Packages
[43.3 kB]
Get:15 http://mirrordirector.raspbian.org jessie/non-free armhf Packages
[84.2 kB]
Get:16 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1,356
B]
Ign http://archive.raspberrypi.org jessie/main Translation-en_CA

Ign http://archive.raspberrypi.org jessie/main Translation-en

Get:17 https://packagecloud.io xenial/main Translation-en_CA [162 B]

Ign http://archive.raspberrypi.org jessie/ui Translation-en_CA

Ign http://archive.raspberrypi.org jessie/ui Translation-en

Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_CA

Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en

Ign http://mirrordirector.raspbian.org jessie/main Translation-en_CA

Ign http://mirrordirector.raspbian.org jessie/main Translation-en

Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_CA

Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en

Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_CA

Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en

Get:18 https://packagecloud.io xenial/main Translation-en [162 B]

Get:19 https://packagecloud.io xenial/main Translation-en_CA [162 B]

Ign https://packagecloud.io xenial/main Translation-en_CA

Get:20 https://packagecloud.io xenial/main Translation-en [162 B]

Ign https://packagecloud.io xenial/main Translation-en

Fetched 9,948 kB in 49s (200 kB/s)
                 _
Reading package lists... Done
W: Duplicate sources.list entry
https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main armhf
Packages
(/var/lib/apt/lists/packagecloud.io_headmelted_codebuilds_ubuntu_dists_xenial_main_binary-armhf_Packages)
W: You may want to run apt-get update to correct these problems
Done!
Installing Visual Studio Code...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  code-oss
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 40.8 MB of archives.
After this operation, 1,478 kB disk space will be freed.
Get:1 https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main
code-oss armhf 1.14.0-1497385449 [40.8 MB]
Fetched 40.8 MB in 48s (840 kB/s)

Reading changelogs... Done
(Reading database ... 146272 files and directories currently installed.)
Preparing to unpack .../code-oss_1.14.0-1497385449_armhf.deb ...
Unpacking code-oss (1.14.0-1497385449) over (1.14.0-1497093446) ...
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Setting up code-oss (1.14.0-1497385449) ...
Visual Studio Code install complete.
Installing git...
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
git install complete.
Installing any dependencies that may have been missed...
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Missed dependency install complete.


Installation complete!

You can start code at any time by calling "code-oss" within a terminal.

A shortcut should also now be available in your desktop menus (depending on
your distribution).


root@raspi3/etc# logout
jacques@raspi3:~$ code-oss
jacques@raspi3:~$ uname -a
Linux raspi3.maison.ca 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017
armv7l GNU/Linux
jacques@raspi3:~$ date
Wed Jun 14 09:44:45 EDT 2017
jacques@raspi3:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 8.0 (jessie)
Release: 8.0
Codename: jessie
jacques@raspi3:~$

**Comment by headmelted** [comment]
Can I ask you to try a fresh install from the script one last time?

I've made changes to the toolchain to use Debian Jessie with emdebian, rather than Ubuntu Ports, which should take the base package versions required back to a release that will hopefully work for everyone (Jessie / Trusty).

**Comment by jadupl2** [comment]
Yes it is Working Now !!!! Great !

I had to set my DISPLAY environment variable (Which I tought was already
set) to make it work.

jacques@raspi3:~$ export DISPLAY=192.168.1.7:0
jacques@raspi3:~$ code-oss

Here is the output of the installation below
Thanks Again

root@raspi3~# date
Fri Jun 16 11:29:07 EDT 2017

root@raspi3~# uname -a
Linux raspi3.maison.ca 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017
armv7l GNU/Linux
root@raspi3~#

root@raspi3~# . <( wget -O - https://code.headmelted.com/installers/apt.sh )

--2017-06-16 11:29:19--  https://code.headmelted.com/installers/apt.sh
Resolving code.headmelted.com (code.headmelted.com)... 104.27.187.80,
104.27.186.80, 2400:cb00:2048:1::681b:ba50, ...
Connecting to code.headmelted.com (code.headmelted.com)|104.27.187.80|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-sh]
Saving to: ‘STDOUT’

-                                         [ <=>
                                          ]   2.29K  --.-KB/s   in 0.001s

2017-06-16 11:29:20 (3.45 MB/s) - written to stdout [2340]

Detecting architecture...
Architecture detected as armv7l...
Installing headmelted GPG key...
OK
Done!
Installing headmelted repository...
deb https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial main
Repository install complete.
Updating APT cache...
Get:1 http://mirrordirector.raspbian.org jessie InRelease [14.9 kB]
Get:2 http://archive.raspberrypi.org jessie InRelease [22.9 kB]
Get:3 http://mirrordirector.raspbian.org jessie/main armhf Packages [9,533
kB]
Get:4 http://archive.raspberrypi.org jessie/main armhf Packages [163 kB]
Get:5 https://packagecloud.io xenial InRelease [23.4 kB]
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Get:6 https://packagecloud.io xenial/main armhf Packages [5,302 B]
Get:7 https://packagecloud.io xenial/main Translation-en_CA [162 B]
Ign http://archive.raspberrypi.org jessie/main Translation-en_CA
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_CA
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:8 https://packagecloud.io xenial/main Translation-en [162 B]
Get:9 https://packagecloud.io xenial/main Translation-en_CA [162 B]
Get:10 http://mirrordirector.raspbian.org jessie/contrib armhf Packages
[43.3 kB]
Get:11 http://mirrordirector.raspbian.org jessie/non-free armhf Packages
[84.2 kB]
Get:12 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1,356
B]
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_CA
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_CA
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_CA
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_CA
Get:13 https://packagecloud.io xenial/main Translation-en [162 B]
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Get:14 https://packagecloud.io xenial/main Translation-en_CA [162 B]
Get:15 https://packagecloud.io xenial/main Translation-en [162 B]
Get:16 https://packagecloud.io xenial/main Translation-en_CA [162 B]
Get:17 https://packagecloud.io xenial/main Translation-en [162 B]
Get:18 https://packagecloud.io xenial/main Translation-en_CA [162 B]
Ign https://packagecloud.io xenial/main Translation-en_CA
Get:19 https://packagecloud.io xenial/main Translation-en [162 B]
Ign https://packagecloud.io xenial/main Translation-en
Fetched 9,891 kB in 50s (196 kB/s)
Reading package lists... Done
W: Duplicate sources.list entry
https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main armhf
Packages
(/var/lib/apt/lists/packagecloud.io_headmelted_codebuilds_ubuntu_dists_xenial_main_binary-armhf_Packages)
W: Duplicate sources.list entry
https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main armhf
Packages
(/var/lib/apt/lists/packagecloud.io_headmelted_codebuilds_ubuntu_dists_xenial_main_binary-armhf_Packages)
W: You may want to run apt-get update to correct these problems
Done!
Installing Visual Studio Code...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  code-oss
1 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 40.8 MB of archives.
After this operation, 229 kB of additional disk space will be used.
Get:1 https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main
code-oss armhf 1.14.0-1497617842 [40.8 MB]
Fetched 40.8 MB in 55s (740 kB/s)
Reading changelogs... Done
(Reading database ... 146079 files and directories currently installed.)
Preparing to unpack .../code-oss_1.14.0-1497617842_armhf.deb ...
Unpacking code-oss (1.14.0-1497617842) over (1.14.0-1497385449) ...
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Setting up code-oss (1.14.0-1497617842) ...
Visual Studio Code install complete.
Installing git...
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
git install complete.
Installing any dependencies that may have been missed...
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Missed dependency install complete.


Installation complete!

You can start code at any time by calling "code-oss" within a terminal.

A shortcut should also now be available in your desktop menus (depending on
your distribution).


root@raspi3~#
root@raspi3~#
root@raspi3~# code-oss
It is recommended to start vscode as a normal user. To run as root, you
must specify an alternate user data directory with the --user-data-dir
argument.
root@raspi3~# code-oss --user-data-dir /home/jacques
It is recommended to start vscode as a normal user. To run as root, you
must specify an alternate user data directory with the --user-data-dir
argument.
root@raspi3~#
root@raspi3~# su - jacques
jacques@raspi3:~$ code-oss
jacques@raspi3:~$

*YES IT IS WORKING*

jacques@raspi3:~$ export DISPLAY=192.168.1.7:0
jacques@raspi3:~$ code-oss
jacques@raspi3:~$

**Comment by carlhung** [comment]
I already installed code-oss
but when i type sudo apt-get update, i got this:

Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Hit https://packagecloud.io xenial InRelease
Hit https://packagecloud.io xenial/main armhf Packages
Get:1 https://packagecloud.io xenial/main Translation-en_HK [162 B]
Get:2 https://packagecloud.io xenial/main Translation-en [162 B]
Get:3 https://packagecloud.io xenial/main Translation-en_HK [162 B]
Get:4 https://packagecloud.io xenial/main Translation-en [162 B]
Get:5 https://packagecloud.io xenial/main Translation-en_HK [162 B]
Ign http://archive.raspberrypi.org jessie/main Translation-en_HK
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_HK
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Get:6 https://packagecloud.io xenial/main Translation-en [162 B]
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_HK
Get:7 https://packagecloud.io xenial/main Translation-en_HK [162 B]
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Get:8 https://packagecloud.io xenial/main Translation-en [162 B]
Ign http://archive.raspberrypi.org jessie/ui Translation-en_HK
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_HK
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:9 https://packagecloud.io xenial/main Translation-en_HK [162 B]
Ign https://packagecloud.io xenial/main Translation-en_HK
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_HK
Get:10 https://packagecloud.io xenial/main Translation-en [162 B]
Ign https://packagecloud.io xenial/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Reading package lists... Done
W: Duplicate sources.list entry https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main armhf Packages (/var/lib/apt/lists/packagecloud.io_headmelted_codebuilds_ubuntu_dists_xenial_main_binary-armhf_Packages)
W: You may want to run apt-get update to correct these problems

how can i fix it?
thanks.

**Comment by headmelted** [comment]
Interesting.. You shouldn't have two entries in there. I may need to put a
check on the script in case of multiple runs.

Open a terminal, and try this:

sudo code-oss /etc/apt/sources.list

Hopefully, VS Code opens up and you see the sources.list file.

Find the FIRST line that ENDS with this:

https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main armhf

(It should look something like this:)

deb [arch=armhf] https://packagecloud.io/headmelted/codebuilds/ubuntu/
xenial/main
armhf

Delete that line from the file after checking that there's a duplicate line
further down.

Once this is done save, exit, and try the update again. If it doesn't work
please reply with the terminal output so I can see what's happening.

Thanks!

**Comment by raspberrypieman** [comment]
I have been following this article to use a 4 pin DHT11 sensor on a Raspberry Pi:
http://www.circuitbasics.com/how-to-set-up-the-dht11-humidity-sensor-on-the-raspberry-pi/#

I have a Raspberry Pi-3 with the latest Jessie installed and wanted to try the Python example:
I did a sudo apt-get-update, then
followed the instructions:
   sudo apt-get install git-core
   git clone https://github.com/adafruit/Adafruit_Python_DHT.git
   cd Adafruit_Python_DHT
   sudo apt-get install build-essential python-dev
   sudo python setup.py install

Then I tried to run the program snippet:
   #!/usr/bin/python
   import sys
   import Adafruit_DHT
   while True:
       humidity, temperature = Adafruit_DHT.read_retry(11, 4)
       print 'Temp: {0:0.1f} C  Humidity: {1:0.1f} %'.format(temperature, humidity)

And got these errors:
Traceback (most recent call last):
  File "dht11_test.py", line 7, in <module>
    humidity, temperature = Adafruit_DHT.read_retry(11, 4)
  File "/home/pi/Adafruit_Python_DHT/Adafruit_DHT/common.py", line 94, in read_retry
    humidity, temperature = read(sensor, pin, platform)
  File "/home/pi/Adafruit_Python_DHT/Adafruit_DHT/common.py", line 80, in read
    platform = get_platform()
  File "/home/pi/Adafruit_Python_DHT/Adafruit_DHT/common.py", line 55, in get_platform
    from . import Raspberry_Pi_2
  File "/home/pi/Adafruit_Python_DHT/Adafruit_DHT/Raspberry_Pi_2.py", line 22, in <module>
    from . import Raspberry_Pi_2_Driver as driver
ImportError: cannot import name Raspberry_Pi_2_Driver

I did another sudo apt-get-update and repeated the process above.
I did notice this message - but do not know how to resolve it:
Reading package lists... Done
W: Duplicate sources.list entry https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial/main armhf Packages (/var/lib/apt/lists/packagecloud.io_headmelted_codebuilds_ubuntu_dists_xenial_main_binary-armhf_Packages)
W: You may want to run apt-get update to correct these problems

How can I resolve the  "W:" messages or 
the "ImportError: cannot import name Raspberry_Pi_2_Driver" messages, 
Please?

Regards

**Comment by headmelted** [comment]
I **_believe_**, although I'm not certain, that this should be resolved with the black-screen fixes in the latest release, but let me know if this is not the case.
