### ISSUE TITLE
Code-OSS failed to highlight on Raspbain 

### ISSUE THREAD

**Issue by C0618C** [headmelted/codebuilds#21]
Thank you for your work on building code on armhf.  

Code-OSS can't highlight js/html/css(and any other,I think). and come out some errors show:`The mode has failed while tokenizing the input.`

There are some information that i think it will be useful below.

- VSCode Version:code-oss_1.13.0-1495354883_armhf
- OS Version: Raspbain Jessie(2017-4-10)

![bug3](https://cloud.githubusercontent.com/assets/24599397/26285308/dee68964-3e7f-11e7-89b4-62fe667a9b5c.png)

What can I do to fix it?

Thx.

**Comment by NTBTI** [comment]
I had the same problem running on a Samsung Chromebook (same armhf processor) using Ubuntu 14.04. I don't have a Pi to try this on so I have no idea if it will work for you or not, but the lower library version problem looks exactly the same.

First I went here https://packages.debian.org/stretch/libstdc++6 and grabbed the .deb file for armhf, unpacked it (ar vx packagilefile.deb) then untarred data.tar.xv (tar xfv data.tar.xv). 
Then copied the new file (in my case it was libstdc++.so.6.0.22) and re-created the symlink to have libstdc++.so.6 now point to libstdc++.so.6.0.22
For good measure I removed ~/.vs-code then purged the installer (no idea if any of this was necessary) and then re-installed. After that no more errors! Hope it helps.

**Comment by xshotD** [comment]
Having same problem - will try @NTBTI solution when my Pi finishes updating.

**Comment by xshotD** [comment]
Actually, turns out I used the solution when updating. Here's my part:

- edit `/etc/apt/sources.list` (needs sudo obvs)
- replace `jessie` with `stretch`
- `sudo apt update`
- `sudo apt upgrade`
Note that this took more than a hour on a RPi 3 with the newest jessie.

But after the upgrade is done - I restarted VS Code and no errors happened.

**Comment by headmelted** [comment]
@xshotD thanks for adding a solution.

Interesting though that this requires a change to stretch to resolve. I'm skeptical that there would be an unpatched bug in Jessie that would cause this, so I'm leaning towards it either being configuration or dependencies related.

I'm working through a couple of build items then I'll get back to looking at this!

**Comment by xshotD** [comment]
Jessie just has a outdated libc6, as noted in the error message in the dev tools - libc6 in Debian/Raspbian Jessie is 2.19 and Stretch is 2.24 in the repos.

**Comment by cuibonobo** [comment]
I tried @NTBTI's solution and it worked just fine without having to reinstall. Just restarting the app worked for me.

**Comment by C0618C** [comment]
@xshotD,I'm sorry to tell you that it doesn't work on my pi.  
I upgrade to the Stretch,then install the OSS,But, the same probrem had come out.  
And wireless interface couldn't find in Stretch.  
  
I had try the way that @NTBTI suggess too.But I don't know how to do with this:
> Then copied the new file (in my case it was libstdc++.so.6.0.22) and re-created the symlink to have libstdc++.so.6 now point to libstdc++.so.6.0.22
+ Where to paste the new file
+ How to re-created the symlink  
Can anyone tell me what cmd would make the magic?

**Comment by headmelted** [comment]
This is interesting.

Two things I would suggest - firstly, can you try the latest version from the script?.  I've been working on a significant re-write of how this works and I'd like to make sure that you and I are both looking at the same build on the same architecture.

If the latest version doesn't work - try this for me in a terminal (the whole line verbatim):

find / -name "libstdc++.so.6"

.. and paste the result back here.

We'll get this sorted quickly - I did have to do some symlinking for this during development so I'm confident it will not be a difficult fix.

**Comment by howprice** [comment]
I'm having the same problem as in the original post on Raspberry Pi 3. Installed and updated last night. I am wary of updating to stretch or trying any hacky fixes.

**sudo find / -name "libstdc++.so.6"**    returns nothing

Is the fix available yet?

**Comment by xshotD** [comment]
is `libc6` installed?

**Comment by headmelted** [comment]
ok - howprice - that's actually good.

Try this for me:

sudo apt-get install -y libstdc++6

Can you post back here the result?

Also - once you've run the above, can you then retry launching?

**Comment by howprice** [comment]
$ sudo apt-get install -y libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by C0618C** [comment]
@headmelted sorry,I'm busy at work.Maybe I would try it later

**Comment by markwrenn** [comment]
It took two tries to get the find command to work:

![image](https://user-images.githubusercontent.com/4588913/27209170-16d88d26-51ff-11e7-83ae-a70778cdcef2.png)

**Comment by headmelted** [comment]
I've done some rework to the cross-compilation toolchain to make it user Debian Jessie (with emdebian) instead Of Ubuntu Xenial (with ports.ubuntu.com) to hopefully resolve this issue.

Can I get you to try a fresh install when you get the chance?  (It should, for example, work with the libstdc++ that you have installed now, but I have no way of guaranteeing that just yet as it works for me anyway.

**Comment by MiShibari** [comment]
I executed `. <( wget -O - https://code.headmelted.com/installers/apt.sh )` again and it works fine on my  RPi3. Thank you very much.

**Comment by headmelted** [comment]
@MiShibari 

Success!  Glad it worked for you. 😃

Incidentally, this change _**should**_ take the minimum Ubuntu release required all the way back to 14.04 (trusty) too.

Can other folks in the thread confirm this fixes it for them too when they get a chance?

Thanks!

**Comment by howprice** [comment]
That's worked for me too. Many thanks.

**Comment by markwrenn** [comment]
Working like a charm!

Thanks for all the work you do on this!

**Comment by headmelted** [comment]
Glad to hear it seems to have done the trick.

I'll close out this thread for now.  If anyone else on the thread experiences this issue, feel free to re-open.

Thanks again for the feedback!

**Comment by bmwertman** [comment]
I'm seeing this issue on my Wheezy Raspberry Pi 2. For some reason when I try to run 

`. <( wget -O - https://code.headmelted.com/installers/apt.sh )` I get an error.

`GnuTLS : A TLS fatal alert has been received`
`Unable to establish SSL connection`

**Comment by tilda** [comment]
That's unrelated to the topic of the issue.
Although, you may have a busted connection or something.

**Comment by bmwertman** [comment]
I realize the wget issue is not directly related. But the only reason I was trying to use wget was because I'm experiencing the same error message from  Code-OSS with regarding highlighting.
