### ISSUE TITLE
Raspberry Pi 3 with Jessie - Install Failed

### ISSUE THREAD

**Issue by macnlkc** [headmelted/codebuilds#32]
Newbie question that I can't seem to get resolved.  

I've attempted the install and get the following error...

Detecting architecture...
Architecture detected as armv7l...
Installing headmelted GPG key...
OK
Done!
Installing headmelted repository...
deb https://packagecloud.io/headmelted/codebuilds/ubuntu/ xenial main
Repository install complete.
Updating APT cache...
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
Done!
Installing Visual Studio Code...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**E: Unable to locate package code-oss
Visual Studio Code install failed.**

Any thoughts?

**Comment by headmelted** [comment]
Try:

sudo apt-get install -y apt-transport-https

(This needs to be done inside the chroot.)

**Comment by existdissolve** [comment]
@headmelted I can confirm that your suggestion resolves the issue. Thanks for this awesome build! :+1:
