### ISSUE TITLE
Use dvorak keyboard layout

### ISSUE THREAD

**Issue by nullset** [headmelted/codebuilds#34]
Hi, I just installed VSCode via your instructions, and it works amazingly well! Thanks for all your hard work! One question though ... I typically use the Dvorak keyboard layout (yes, I'm one of _those_ people) and I can't figure out how to start the chroot for VS Code with the keyboard of my choice. Any pointers?

**Comment by DanielFallon** [comment]
you should be able to enter the chroot manually using enter-chroot, see the crouton documentation for more details on that

once inside, this build is based on ubuntu. The command to fix it I believe looks like this?
```
setxkbmap -layout us,us -variant dvorak
```

**Comment by nullset** [comment]
Great, thanks for the help. Unfortunately when trying to do that I only get an error back `Cannot open display "default display"`. Looking on various forums it appears that it may be an issue with Xiwi, as I've not seen anything that definitively fixes the issue.

**Comment by magic-k** [comment]
You closed this issue a bit prematurely. Yes it's a xiwi thing but there's a ~/.xiwirc exact for that. The problem ist, that setxkbmap needs an xserver so you can't set the language in a terminal. I have the following in my ~/.xiwirc
_setxkbmap de_

With that i can start vscode with startxiwi and have german keyboard layout.
