### ISSUE TITLE
Is codebuilds still maintained?

### ISSUE THREAD

**Issue by ghost** [headmelted/codebuilds#48]
Hi,

I recently discovered codebuilds via twitter and afer I tried to install it on my Rapsberry Pi 3 and failed I wonder if codebuilds ist stll maintained since all open issues here are older and the last release  on packagecloud.io was based on code 1.14 and is nine months old
Is there anyway to contributed or help codebuilds?

**Comment by headmelted** [comment]
Hi, sorry for the late reply. I've been working on some big changes here.

I'll be releasing the updates (hopefully) within the next week.

**Comment by headmelted** [comment]
Hi, the latest packages should be working for you now :-)

**Comment by headmelted** [comment]
Family matters intervened to prevent me from getting the build pipeline in the last few months but it should now be back up and rolling!
