### ISSUE TITLE
v1.28.0 shows blank window on Raspberry Pi3B

### ISSUE THREAD

**Issue by DirkUK** [headmelted/codebuilds#56]
I am using Code on a Pi3B, running Rasbian Stretch. Code 1.14 was running fine on this system.

After updating to v1.28 (including current 1.28.0-1536884861_arnhf) the main window stays blank, and just the main menu is showing. Most menu entries do not work (apart from some of the help menu entries). 
When I downgrade to 1.14 everything works again.

I'm trying to find a log, but I cannot find any. A new directory is created in ~/config/Code - OSS/logs on every start, but no log file is created there.

**Comment by dotiylk** [comment]
Appreciate for the update, same blank window at v1.28.0.
Running up-to-date Raspbian Stretch with Raspberry Pi 3b+.

**Comment by magic-k** [comment]
@DirkUK start code-oss with `--verbose --log debug`

**Comment by DirkUK** [comment]
Output of `file`:
`/usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=f48d0b31ab2fe4b41ed2db0992a092a2533644f0, not stripped`
So it seems to be an x86-64 file.

**Comment by DirkUK** [comment]
Just tried the latest version (code-oss_1.28.0-1537600050_armhf.deb) and the problem seems to be solved!

Thanks  @headmelted !

**Comment by headmelted** [comment]
Glad it helped!!
