### ISSUE TITLE
I can't seem to install extensions with the new version

### ISSUE THREAD

**Issue by Yamboy1** [headmelted/codebuilds#57]
I've just recently ugraded my code version from 1.14 to 2.28 and am having trouble installing extensions.
I did a bit of research and found out whats wrong.

https://github.com/Microsoft/vscode/issues/42204
https://github.com/Microsoft/vscode/issues/2647#issuecomment-269403183

However, having looked at your `product.json`, I do indeed see the `extensionsGallery` urls. What could be the problem

**Comment by headmelted** [comment]
This one's very definitely my fault I'm afraid.

During the build, I make some patches to Microsoft's OSS code to restore things like extensions (_the extensions support from product.json is only included in their release builds, and needs to be explicitly enabled in the OSS version_).

I removed the patches to get the builds and scripts fixed back up, but I expect to the patches restored by this evening - I'll close the issue and update when this is ready.

**Comment by DirkUK** [comment]
Seems to be solved now. At least I did not have to rip the missing bits from a backup of product.json this time :) (using code-oss_1.28.0-1537780162_armhf.deb)

**Comment by magic-k** [comment]
I completely  removed my code-oss installation and reinstalled the arm64-deb. Extensions work, so i guess it is resolved.

**Comment by headmelted** [comment]
Glad to hear it!

You're getting these re-tested quicker than I can update the tickets. It's
great! :-)

**Comment by Yamboy1** [comment]
Sorry my reply is so late, but the new update does certainly work now :+1:

**Comment by headmelted** [comment]
Glad to hear it and thanks for letting me now 🙂
