### ISSUE TITLE
Install crash but finish and black window

### ISSUE THREAD

**Issue by cyvocross** [headmelted/codebuilds#73]
Hi when i try to install code-oss by sudo apt-get install code-oss, during stilla i recieved this message before ending : 
Ign https://packagecloud.io stretch/main Translation-en
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
done!

but when code-oss lanch but still with back windows without menu or something like else (raspian on raperry 3b+).

regards,

**Comment by Silerra** [comment]
The problem with black window is already discussed in another issue. You can try an older version. See this: https://github.com/headmelted/codebuilds/issues/67#issuecomment-466255567

**Comment by Vifier-Lockla** [comment]
I had the same thing on Raspberry PI 3 B+ : I soluced few minutes ago after those commands from terminal :

sudo apt-get update
...
sudo apt-get upgrade
...
code-oss
.... and surprise : it works !!! In fact libraries on my Raspberry PI weren't the last...

I will try to reinstall last version of code-oss just to valid this sentence : "Before install code-oss, assume you upgraded before the libraries (absolutely all) of your Raspberry PI !!!" ...

**Comment by headmelted** [comment]
The black window issue is now resolved, and it sounds like the dpkg issue has gone too?

Closing thread as I believe this is resolved now, please let me know if that’s not the case and I’ll re-open.
