### ISSUE TITLE
Blank window after successful Installation (Raspberry Pi 4 & Pi 3B+)

### ISSUE THREAD

**Issue by baermathias** [headmelted/codebuilds#79]
Device: Raspberry Pi 4
code-oss version: newest version using `apt.sh` installer script:
```
wget https://packagecloud.io/headmelted/codebuilds/gpgkey -O - | sudo apt-key add -
curl -L https://code.headmelted.com/installers/apt.sh | sudo bash

```
After uninstalling it and re-installing an older version `apt-get install code-oss=1.29.0-1539702286` it works, but this version is a pretty old one! 

Has anybody an idea why the newer versions don't work?

**Comment by Vifier-Lockla** [comment]
I had the same thing on Raspberry PI 3 B+ : I soluced few minutes ago after those commands from terminal : 
> sudo apt-get update
...
> sudo apt-get upgrade
...
> code-oss
.... and surprise : it works !!! In fact libraries on my Raspberry PI weren't the last...

I will try to reinstall last version of code-oss just to valid this sentence : "Before install code-oss, assume you upgraded before your Raspberry PI !!!" ...

**Comment by voidbrain** [comment]
Same for me on brand new Raspberry Pi 4:
i tried `update` & `upgrade` and then reinstalled with 
`wget https://packagecloud.io/headmelted/codebuilds/gpgkey -O - | sudo apt-key add -
curl -L https://code.headmelted.com/installers/apt.sh | sudo bash`
but i always get the blank screen. What can I do?

**Comment by Vifier-Lockla** [comment]
> Same for me on brand new Raspberry Pi 4:
> i tried update & upgrade and then reinstalled with
> wget https://packagecloud.io/headmelted/codebuilds/gpgkey -O - | sudo apt-key add - curl -L https://code.headmelted.com/installers/apt.sh | sudo bash
> but i always get the blank screen. What can I do?

I received RPI 4 today, I will try this evening to install code-oss.
Just a question, can you confirm the version of code-oss you are using...normally last one but other post showed only version 1.29.0-1539702286 run properly on RPI (not 1.32.xxx).

verify with the command following :
`> apt list code-oss`

See this post to understand my answer : https://github.com/headmelted/codebuilds/issues/64

and apply that below if you don't have the 1.29.0-1539702286 version  👍 

1. To Remove The Failing Build
`> sudo apt-get purge code-oss`

2. To install Downgrade
`> sudo apt-get install code-oss=1.29.0-1539702286`

3. To prevent Downgrade from Updating Automatically
`> sudo apt-mark hold code-oss`

**May be later …**

4. To Undo Step 3
`> sudo apt-mark unhold code-oss`

**Comment by Vifier-Lockla** [comment]
# Installation on RPI 4B - Successfull !!!

## 1. Install Code-oss :

**First** : Declare repository
<pre>curl -s https://packagecloud.io/install/repositories/headmelted/codebuilds/script.deb.sh | sudo bash</pre>

**Second** : Install code-oss
<pre>curl -L https://code.headmelted.com/installers/apt.sh | sudo bash</pre>

## 2. Change Code-OSS version (Downgrad from 1.32.x to 1.29.y to avoid empty window)

1.  To Remove the current version

    <pre>sudo apt-get purge code-oss</pre>

2. To install new version

    <pre>sudo apt-get install code-oss=1.29.0-1539702286</pre>

3. To prevent Downgrade from Updating Automatically

    <pre>sudo apt-mark hold code-oss</pre>

The result for me :

![2019-08-03-143751_1920x1080_scrot](https://user-images.githubusercontent.com/13519215/62413691-23ee5800-b612-11e9-83f0-6e1591672929.png)

**Comment by ospersson** [comment]
@Vifier-Lockla Your solution worked great! I'm using the RPI 4B 4GB model. 

Version: 1.29.0 (user setup)
Commit: f74c7914490b68b4052ff877f04b6eaf7198f261
Date: 2018-10-16T15:00:48.287Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: arm

**Comment by vthorsteinsson** [comment]
Would be good to know when this is fixed; although 1.29 works reasonably well on the RPi 4, it is not bug free (for instance windows resizing is sometimes erratic).

**Comment by tjohnsonhvac** [comment]
I have tried installing on a RPI 3B+ with Raspbian Buster and an Asus Tinkerboard running Armbian: 
Linux tinkerboard 4.4.190-rockchip #4 SMP Mon Sep 2 07:28:49 CEST 2019 armv7l armv7l armv7l GNU/Linux

I get a blank screen on both devices following the official install instructions.
I did not find this post until my second attempt on the Tinkerboard. downgrading to 1.29 also fixes the issue for me. 

If there is any way to get debug info from code-oss when starting the application, I'm willing to do some work tackling the issue. Maybe someone can point me in a direction to get started...

**Comment by madzim** [comment]
@baermathias 
Back in july, you renamed this to include `(Raspberry Pi 4)`.

I'm on Pi 3+; I experienced the same blank/black screen when installing the 1.32 problem. The solutions provided above to downgrade to 1.29 worked for me as well.

Would you consider appending the title to include Pi 3B+?

**Comment by headmelted** [comment]
Fixed this in the latest builds, finally.  An apt update should be all that’s required to bring this back up and have the latest build running.
