### ISSUE TITLE
Title: Release server sends application/json MIME type for package downloads

### ISSUE THREAD

**Issue by ghost** [headmelted/codebuilds#8]
Steps to reproduce:

1. Visit https://code.headmelted.com/#linux-header-manual
2. Click link for "code-oss_1.8.0-2016112710_amd64.deb" download

Expected results:

I'm prompted to install deb with the "Software Install" app

Actual results:

Server sends package with application/json MIME type, so I'm prompted to open
with gedit, instead.

Additional details:

Clicking on the other links (e.g., RPMs) gives the same results.

Also, minor nitpick: the arch lists for the debs and RPMs are listed in a
different order.

**Comment by headmelted** [comment]
I'll get a look at the package ordering and change it so that the both formats are the same.

Insofar as the MIME headers go, the hosting is done by bintray, and you may have picked up on something they aren't yet aware of here.

**Comment by headmelted** [comment]
I've switched recently from Bintray to packagecloud for hosting the packages.  As a result the link now points directly to packagecloud's repository for the built packages, so is no longer held on the code.headmelted.com page.
