### ISSUE TITLE
VSCode on Raspberry Pi 4B?

### ISSUE THREAD

**Issue by kauailabs** [headmelted/codebuilds#80]
Anyone know of a codebuild that runs on Raspberry  Pi 4B?

With the new processor and now 4GB of RAM, I'm thinking we've finally reached a point where direct development in VSCODE should be realistic and perform reasonably.  I've tried the latest build, but am not having much success at all, after having tried versions 1.29 - 1.32.  I am able to get v. 1.29 to run on Raspberry  PI 3B+, similar to others - but the performance is rather dreadful.  So with high hopes for Raspberry Pi 4B, has anyone had any success or have any  suggestions?

**Comment by pokekey** [comment]
Following instructions in #79, I was able to get 1.29 to run on PI 4B (4GB) and the performance is credible.  My favorite editor now on the RPI.

**Comment by magic-k** [comment]
As microsoft has released an armhf server build for remote ssh in insiders, whats the point in running code native on the raspi?

**Comment by pokekey** [comment]
A. `remote ssh in insiders` huh?  I've heard about this remoting thing and some day I plan to study up on it but I'm not an insider and don't know how to use it.
B. I want to edit files on the RPI such as documentation, configuration, and maybe even source code.
C. Simpler to use just one computer.

**Comment by devax** [comment]
@magic-k For (young) students it is great to use a Pi to take their first steps into programming. It's a great way to play around without having to worry about breaking dad's computer. Would be nice to have an up to date VS Code on the Pi again.

**Comment by kipters** [comment]
@magic-k what if you want to use the raspi to remote **into** a beefier machine somewhere else?

**Comment by martinrbowman** [comment]
> 
> 
> As microsoft has released an armhf server build for remote ssh in insiders, whats the point in running code native on the raspi?

Yes they have, but, if you are hoping to use C++ there are issues in that the cpptools currently do not support ARM architecture. SO if you are hoping to use C++ either directly or remote you may have to wait a little while.

If you want this feature, let Microsoft know (the more people ask) the more likely it is to get tabled.

**Comment by ellisnet** [comment]
Just a note to say that as of 10-Dec-2019, I installed Code-OSS on a Raspberry Pi 4B (4GB RAM) using the [standard instructions](https://code.headmelted.com/#linux-install-scripts) and it appears to be working fine.  I have Raspbian Buster 32-Bit (`uname -m` reports `armv7l`) installed via NOOBS 3.2.1.  Checking Help > About in Code-OSS reports version `1.42.0 (user setup)`

I hope that is helpful to people who are monitoring this issue, or people (like me) who find it and wonder whether they can install VSCode on Raspberry Pi 4B.

**Comment by headmelted** [comment]
I’ve been updating some other tickets to say that the builds should now be fixed and up-to-date, so I’m glad to hear that this is working for you again!
