### ISSUE TITLE
Latest VSCode Releases Missing (e.g. 1.37)

### ISSUE THREAD

**Issue by Ben0mega** [headmelted/codebuilds#84]
Unclear if this is due to the Azure Pipelines Failed on the website, but VSCode is on release 1.37, and the downloads only have 1.32.  Is there any chance of later versions being made available?  Is there something I could do to help make them available?

I would try to debug the Azure pipeline failure, but its not a link and I have no idea how to see the failure.

Release announcement for 1.37: https://code.visualstudio.com/updates/v1_37

**Comment by Ben0mega** [comment]
And, of course, after posting I was able to find a link - it looks like gulp-gzip is missing.  Let me see if I can add it in a pull request

**Comment by Ben0mega** [comment]
On second read-through, it looks like the package.json is always going to be out-of-date in that folder.  Maybe the changes that are necessary for building debs or rpms should be a patch to the package.json file and then fail in `build.sh` when the patch fails to apply?

**Comment by magic-k** [comment]
I played around with the old travis build system (before azure). I removed the package.json completely and use the one from the vscode repo. Builds out of the box. I just have to keep track of node versions changes. I'm not sure what the intention behind the own package.json was.

**Comment by rhyst** [comment]
Have you managed to get up to date builds working? I'm looking for an arm64 version >1.33.

**Comment by magic-k** [comment]
Just click on my profile.

**Comment by robertely** [comment]
@magic-k Any chance you could file a PR? Be nice to try to get the repos updated.

**Comment by magic-k** [comment]
@robertely My build chain is based on a very old version of headmelteds. I took the old travis version and ported it to github actions. You can get a working current arm64 version from my repo but i have no idea what is not working in the current azure version. But i have seen signs of life from headmelted in this repo so maybe he has found some time to bring it up to date.
As i have moved from arm to intel i can no longer test the arm version. I will build it until headmelted has fixed his build chain.

**Comment by robertely** [comment]
@magic-k Understandable, thanks for the help!

Looks like your not the only one putting out similar builds btw: https://packagecloud.io/swift-arm/vscode/packages/raspbian/buster/code-oss_1.38.1-1568882021_armhf.deb

**Comment by magic-k** [comment]
@robertely Yes, i found a few but they were either abandoned at an old version or produce only armhf (32bit) binaries. I needed arm64.

**Comment by headmelted** [comment]
Hi, this should now be up-to-date and building again. I was gone for a while dealing with some family matters but back on this now!

@magic-k I had no idea you’d had to go to such lengths to get a working build because I hadn’t updated. Sorry about that!  If you ever spot anything and want to raise a PR I’d be happy to merge it in as quick as I can.

**Comment by magic-k** [comment]
Actually it was fun getting this automated build chain going, starting from travis and later migrating to github actions. I learned a lot from it. So from my end all ist good :-)
