### ISSUE TITLE
Multiple problems with Raspbian "buster"

### ISSUE THREAD

**Issue by mojoTX** [headmelted/codebuilds#86]
I found several issues, and I'm typing this on my son's new Raspberry Pi 4. I will see about submitting a pull request to at least fix the apt.sh script later. 

**TL;DR:**

1. The `apt.sh` script needs to use `curl -L` to download the GPG key to handle the 302 redirect.
1. A newer version of Visual Studio Code needs to be built to fully support the latest version of Raspbian, which is derived from the Debian 10 "buster" release. Currently, the script is specifying "stretch", and downloading version `1.32.0-1550644722`, which just gives a black screen on a Raspberry Pi 4 running the latest version of Raspbian. I saw someone mention something about rolling back to an older version, but REALLY? Visual Studio Code is a rapidly-evolving product, and version 1.38 is the current version as of now (Sep 2019)--why would you want to use a version even older?

**Comment by mzinner** [comment]
It would really be great to get the builds updated for Raspbian "buster". Especially the VSCode 1.40 release did a lot of cleanup work and it would make the Raspberry Pi 4 so much more useful to have a recent version of VSCode available there.

**Comment by samuela** [comment]
Also facing the blank screen issue on Raspbian buster on a RPi 4.

**Comment by headmelted** [comment]
New debian packages will be pushed soon (i.e. today, hopefully).

Will test this evening when I get home on Pi 4.

**Comment by headmelted** [comment]
I’ve adopted the curl -L fix from above, nice catch!

The black screen issue should also be resolved by the latest build, let me know if this is not the case!

**Comment by mzinner** [comment]
Thanks for fixing this, it's working great!

**Comment by headmelted** [comment]
Glad to hear it!
