### ISSUE TITLE
Release version is at 1.42, newer than upstream

### ISSUE THREAD

**Issue by alexdewar** [headmelted/codebuilds#91]
It's not obvious to me which upstream version this corresponds to as upstream is only on the 1.40 series. Version 1.40.2, perhaps?

**Comment by magic-k** [comment]
These are nightlies, the official release branch is already at 1.41 but not yet released and the master branch is already on 1.42.

**Comment by headmelted** [comment]
Pretty much as magic-k has said above - the builds track the master branch directly so may be ahead of official builds by a minor version number or two at any given time.

**Comment by alexdewar** [comment]
Ahh I see. Thanks for getting back to me.
